name: Block merge based on time
description: You can prevent your members from merging pull requests during the specified time.
inputs:
  after:
    description: The time to start blocking merging
    required: true
  before:
    description: The time to stop blocking merging
    required: true
  timezone:
    description: Time zone to use. Default is UTC
    required: true
    default: UTC
  prohibited-days-dates:
    description: The days or dates to stop blocking merging all day
    required: false
    default: ""
  no-block-label:
    description: The label to indicate the pull request should not be blocked
    required: false
    default: no-block
  commit-status-context:
    description: The commit status context
    required: false
    default: block-merge-based-on-time
  commit-status-description-with-success:
    description: The commit status description shown with success
    required: false
    default: The PR could be merged
  commit-status-description-while-blocking:
    description: The commit status description shown while blocking
    required: false
    default: The PR can't be merged based on time, which is due to your organization's policy.
  token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
outputs:
  result:
    description: The result of this action
runs:
  using: node12
  main: dist/index.js
